import type { IndustrySlug } from '$lib/industries';

/**
 * Single source of truth: Notion Industry values → demo slug.
 * Add any value that might appear in your Notion "Industry" select;
 * normalization is lowercase and spaces → hyphens (e.g. "Real Estate" → "real-estate").
 */
export const NOTION_INDUSTRY_TO_SLUG: Record<IndustrySlug, readonly string[]> = {
	healthcare: [
		'healthcare',
		'health',
		'health care',
		'medical',
		'clinic',
		'family practice',
		'family medicine',
		'physician',
		'doctor',
		'health services',
		'hospital',
		'nursing',
		'nurse',
		'urgent care',
		'walk-in',
		'medical center',
		'primary care',
		'pediatrics',
		'physiotherapy',
		'physical therapy',
		'chiropractic',
		'chiropractor',
		'optometry',
		'optometrist',
		'eye care',
		'mental health',
		'therapy',
		'therapist',
		'counseling',
		'psychologist',
		'psychiatrist',
		'allergy',
		'cardiology',
		'dermatology',
		'general practice'
	],
	dental: [
		'dental',
		'dentist',
		'dentistry',
		'dental care',
		'dental clinic',
		'orthodontics',
		'orthodontist',
		'oral health',
		'periodontist',
		'endodontist',
		'oral surgeon',
		'dental hygienist',
		'cosmetic dentistry',
		'teeth whitening',
		'implants',
		'pediatric dentist'
	],
	construction: [
		'construction',
		'contractor',
		'general contractor',
		'building',
		'renovation',
		'remodeling',
		'home improvement',
		'contracting',
		// Trades & home services (same theme/images as construction: rugged, industrial)
		'plumbing',
		'plumber',
		'plumbers',
		'hvac',
		'heating',
		'cooling',
		'electrical',
		'electrician',
		'electricians',
		'roofing',
		'roofer',
		'landscaping',
		'landscaper',
		'painting',
		'painter',
		'flooring',
		'carpentry',
		'carpenter',
		'masonry',
		'drywall',
		'handyman',
		'home services',
		'trade',
		'trades',
		'locksmith',
		'locksmiths',
		'hardware store',
		'hardware_store',
		'auto repair',
		'auto mechanic',
		'mechanic',
		'garage',
		'appliance repair',
		'pest control',
		'exterminator',
		'moving company',
		'movers',
		'security systems',
		'garage door',
		'fire protection',
		'sprinkler systems'
	],
	salons: [
		'salons',
		'salon',
		'hair',
		'hair salon',
		'beauty',
		'beauty salon',
		'barber',
		'barbershop',
		'spa',
		'spa & sauna',
		'sauna',
		'infrared sauna',
		'day spa',
		'wellness spa',
		'stylist',
		'hairstylist',
		'cosmetology',
		'nail salon',
		'nails',
		'nail tech',
		'nail technician',
		'esthetician',
		'esthetics',
		'skincare',
		'makeup',
		'makeup artist',
		'beauty services',
		'hair care',
		'massage',
		'massage therapy',
		'waxing',
		'brow',
		'eyelash',
		'lash'
	],
	professional: [
		'professional',
		'professionals',
		'solo-professionals',
		'solo professionals',
		'solo professional',
		'consulting',
		'consultant',
		'ai automation',
		'ai',
		'automation',
		'lead-rosetta',
		'tech',
		'technology',
		'professional services',
		'coach',
		'coaching',
		'business coach',
		'life coach',
		'accounting',
		'accountant',
		'financial advisor',
		'bookkeeping',
		'virtual assistant',
		'freelance',
		'freelancer',
		'design',
		'designer',
		'graphic design',
		'web design',
		'developer',
		'software',
		'photography',
		'photographer',
		'videography',
		'writer',
		'copywriter',
		'editing',
		'transcription',
		'translation',
		'translator',
		'insurance',
		'insurance agent',
		'other'
	],
	'real-estate': [
		'real-estate',
		'real estate',
		'realty',
		'realtor',
		'real estate agent',
		'property',
		'broker',
		'mortgage',
		'real estate broker',
		'real estate agency',
		'property management',
		'property manager',
		'home staging',
		'title company',
		'landlord',
		'property development'
	],
	legal: [
		'legal',
		'law',
		'lawyer',
		'attorney',
		'law firm',
		'legal services',
		'paralegal',
		'estate planning',
		'family law',
		'immigration',
		'litigation',
		'corporate law',
		'criminal defense',
		'legal aid',
		'notary',
		'notary public',
		'divorce',
		'bankruptcy',
		'personal injury',
		'immigration lawyer'
	],
	fitness: [
		'fitness',
		'gym',
		'gyms',
		'personal training',
		'personal trainer',
		'wellness',
		'yoga',
		'pilates',
		'crossfit',
		'studio',
		'sports',
		'fitness center',
		'fitness club',
		'martial arts',
		'boxing',
		'dance studio',
		'dance',
		'cycling',
		'spinning',
		'weightlifting',
		'nutrition',
		'boot camp',
		'aerobics',
		'personal fitness'
	]
};

function normalize(value: string): string {
	return value.toLowerCase().trim().replace(/\s+/g, '-');
}

let _lookup: Map<string, IndustrySlug> | null = null;

function buildLookup(): Map<string, IndustrySlug> {
	if (_lookup) return _lookup;
	_lookup = new Map();
	for (const [slug, values] of Object.entries(NOTION_INDUSTRY_TO_SLUG)) {
		for (const v of values) {
			_lookup.set(normalize(v), slug as IndustrySlug);
		}
	}
	return _lookup;
}

/**
 * Map a Notion Industry select value (any casing/spacing) to the demo URL slug.
 * Unknown values default to 'professional' (broad catch‑all) so demos still work.
 */
export function notionIndustryToSlug(notionValue: string): IndustrySlug {
	if (!notionValue?.trim()) return 'professional';
	const key = normalize(notionValue);
	return buildLookup().get(key) ?? 'professional';
}
